---
# params
# OUTPUT:
#   - output_file: file path where to store the JSON result of win_updates module
- hosts: all
  # avoid polluting even more the guest
  gather_facts: no
  pre_tasks:
    - name: Wait for guest connection
      wait_for_connection:
        timeout: 900
      tags:
        - always
  roles:
    - role: search
      tags:
        - search
    - role: update
      tags:
        - update
