---
# params
# output_file: file path where to store the JSON result of win_updates module
- hosts: all
  # avoid polluting even more the guest
  gather_facts: no
  tasks:
    - name: searching for updates
      win_updates:
        state: searched
        category_names:
          # default categories
          - "CriticalUpdates"
          - "SecurityUpdates"
          - "UpdateRollups"
          # additonal categories
          - "Updates"
          - "Windows 10"
          - "Windows 10 LTSB"
          - "Upgrades"
          - "Definition Updates"
          - "Microsoft Defender Antivirus"
      register: wu_state

    - name: write search results to a file
      local_action:
        module: copy
        content: "{{ wu_state }}"
        dest: "{{ output_file }}"
